name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Adjust as necessary

      - name: Install Dependencies
        run: npm install
        working-directory: ./src # Specify working directory

      - name: Build
        run: npm run build
        working-directory: ./src # Specify working directory
        env:
          # If you have environment variables to include
          VITE_BASE_URL: "/us-census-language/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/dist # Adjust the path to the build output directory
